ARG source_image
FROM ${source_image}
ENV RAILS_ENV=test
COPY --chown=app:app ./spec /home/app/api/spec
COPY --chown=app:app ./.rspec /home/app/api/.rspec
COPY --chown=app:app ./.rspec_parallel /home/app/api/.rspec_parallel
COPY --chown=app:app ./.rubocop.yml /home/app/api/.rubocop.yml
COPY --chown=app:app ./.rubocop_todo.yml /home/app/api/.rubocop_todo.yml
USER root
RUN apk add --no-cache --virtual .build-tools git build-base curl-dev nodejs yarn && \
    cd /home/app/api && \
    bundle install --no-cache --jobs=5 --retry=3 --without=development --with=production test --deployment && \
    apk del .build-tools && \
    chown -R app:app /home/app/api/vendor/bundle
## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
USER app
CMD ["sh", "-c", "/wait && bundle exec rake db:create db:migrate && bundle exec rspec"]
