base:
  applicationPort: 8080
  readinessPath: /ping.json
  livenessPath: /ping.json
  startupPath: /ping.json
  image: 'hmctspublic.azurecr.io/et-pet/api:latest'
  ingressHost: et-pet-api.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: api-pet
  environment:
    RAILS_ENV: 'production'
