assign_root_object_to_commands:
  cron: "0 0 12 * *"
  class: "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper"
  description: "AssignRootObjectToCommandsJob"
  args:
    -
      job_class: AssignRootObjectToCommandsJob
      arguments:
        -
housekeeping:
  cron: "0 2 * * *"
  class: "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper"
  description: "HousekeepingJob"
  args:
    -
      job_class: HousekeepingJob
      arguments:
        -
