test:
  service: Disk
  root: <%= Rails.root.join("tmp/test_storage#{ENV['TEST_ENV_NUMBER']}") %>

local:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local_direct_upload:
  service: Disk
  root: <%= Rails.root.join("tmp/direct_upload_storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
azure:
  service: AzureStorage
  storage_account_name: <%= ENV.fetch('AZURE_STORAGE_ACCOUNT', 'devstoreaccount1') %>
  storage_access_key: <%= ENV.fetch('AZURE_STORAGE_ACCESS_KEY', 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==') %>
  container: <%= ENV.fetch('AZURE_STORAGE_CONTAINER', 'et_api_container') %>
  <%= "use_path_style_uri: true" if ENV.fetch('AZURE_STORAGE_BLOB_FORCE_PATH_STYLE', 'false') == 'true' %>
  <%= "storage_blob_host: '#{ENV['AZURE_STORAGE_BLOB_HOST']}'" if ENV.key?('AZURE_STORAGE_BLOB_HOST') %>
azure_direct_upload:
  service: AzureStorage
  storage_account_name: <%= ENV.fetch('AZURE_STORAGE_DIRECT_UPLOAD_ACCOUNT', 'devstoreaccount1') %>
  storage_access_key: <%= ENV.fetch('AZURE_STORAGE_DIRECT_UPLOAD_ACCESS_KEY', 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==') %>
  container: <%= ENV.fetch('AZURE_STORAGE_DIRECT_UPLOAD_CONTAINER', 'et_api_container') %>
  <%= "use_path_style_uri: true" if ENV.fetch('AZURE_STORAGE_BLOB_FORCE_PATH_STYLE', 'false') == 'true' %>
  <%= "storage_blob_host: '#{ENV['AZURE_STORAGE_BLOB_HOST']}'" if ENV.key?('AZURE_STORAGE_BLOB_HOST') %>
azure_test:
  service: AzureStorage
  storage_account_name: <%= ENV.fetch('AZURE_STORAGE_ACCOUNT', 'devstoreaccount1') %>
  storage_access_key: <%= ENV.fetch('AZURE_STORAGE_ACCESS_KEY', 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==') %>
  container: <%= ENV.fetch('AZURE_STORAGE_CONTAINER', 'et-api-test-container') %><%= ENV['TEST_ENV_NUMBER'] %>
  <%= "use_path_style_uri: true" if ENV.fetch('AZURE_STORAGE_BLOB_FORCE_PATH_STYLE', 'true') == 'true' %>
  storage_blob_host: <%= ENV.fetch('AZURE_STORAGE_BLOB_HOST', 'http://localhost:10000') %>
azure_test_direct_upload:
  service: AzureStorage
  storage_account_name: <%= ENV.fetch('AZURE_STORAGE_DIRECT_UPLOAD_ACCOUNT', 'devstoreaccount1') %>
  storage_access_key: <%= ENV.fetch('AZURE_STORAGE_DIRECT_UPLOAD_ACCESS_KEY', 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==') %>
  container: <%= ENV.fetch('AZURE_STORAGE_DIRECT_UPLOAD_CONTAINER', 'et-api-direct-test-container') %><%= ENV['TEST_ENV_NUMBER'] %>
  <%= "use_path_style_uri: true" if ENV.fetch('AZURE_STORAGE_BLOB_FORCE_PATH_STYLE', 'true') == 'true' %>
  storage_blob_host: <%= ENV.fetch('AZURE_STORAGE_BLOB_HOST', 'http://localhost:10000') %>


# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
